export enum EEventTypes {
  DISPLAY_WIDGET = 'DISPLAY_WIDGET',
  ON_CLICK = 'ON_CLICK',
  ON_SELECT = 'ON_SELECT'
}

export enum EActionTypes {
  DISPLAY_FORM = 'DISPLAY_FORM',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE'
}

export enum EActionUseWhenType {
  ALWAYS = 'ALWAYS',
  SELECTED_ONE = 'SELECTED_ONE',
  SELECTED_MANY = 'SELECTED_MANY',
  FILLED = 'FILLED'
}
